[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'glidenote/memolist.vim'
if = '''has('mac') || has('win32unix')'''

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'wavded/vim-stylus'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
