
# tap repositories and their packages

tap homebrew/core
brew ant
brew apr
brew apr-util
brew asciinema
brew autoconf
brew automake
brew awscli
brew bash
brew bash-completion
brew boost
brew cairo
brew cmake
brew coreutils
brew ctags
brew czmq
brew docker
brew doxygen
brew faac
brew fdk-aac
brew ffmpeg --with-fdk-aac --with-libass --with-libsoxr --with-libvidstab --with-opencore-amr --with-openjpeg --with-openssl --with-rtmpdump --with-sdl2 --with-tools --with-x265 --with-fontconfig --with-freetype --with-frei0r --with-libbluray --with-libcaca --with-libvorbis --with-libvpx --with-opus --with-speex --with-theora
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew gawk
brew gcc
brew gdbm
brew gettext
brew git
brew glib
brew gmp
brew go
brew gobject-introspection
brew graphite2
brew harfbuzz
brew highlight
brew icu4c
brew imagemagick --with-fontconfig
brew intltool
brew isl
brew jemalloc
brew jpeg
brew jq
brew lame
brew libass
brew libbluray
brew libcaca
brew libevent
brew libffi
brew libidn2
brew libmpc
brew libogg
brew libpng
brew libsodium
brew libsoxr
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvidstab
brew libvorbis
brew libvpx
brew libvterm
brew libyaml
brew little-cms2
brew lua
brew luajit
brew mas
brew mpfr
brew msgpack
brew mysql
brew nasm
brew neovim
brew nkf
brew nodebrew
brew oniguruma
brew openblas
brew opencore-amr
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew pango
brew pcre
brew peco
brew perl
brew pixman
brew pkg-config
brew postgresql
brew pyenv
brew pyenv-virtualenv
brew python
brew python3
brew qt
brew rbenv
brew readline
brew rlog
brew rlwrap
brew rtmpdump
brew ruby
brew ruby-build
brew s3cmd
brew sdl
brew sdl2
brew speex
brew sqlite
brew texi2html
brew texinfo
brew the_platinum_searcher
brew theora
brew tmux
brew translate-shell
brew tree
brew unibilium
brew utf8proc
brew vim --with-lua
brew wget
brew x264
brew x265
brew xvid
brew xz
brew yasm
brew zeromq
brew zlib

tap homebrew/apache

tap homebrew/dupes

tap homebrew/science

tap homebrew/versions

tap caskroom/cask
cask rstudio
cask slack
cask gyazo
cask readcube
cask qlmarkdown
cask betterzip
cask r-app
cask macvim
cask vlc
cask skype
cask appcleaner
cask karabiner-elements
cask qlvideo
cask handbrake
cask kindlegen
cask chrome-remote-desktop-host
cask suspicious-package
cask evernote
cask scriptql
cask the-unarchiver
cask google-photos-backup-and-sync
cask dropbox
cask macs-fan-control
cask coteditor
cask cooviewer
cask kindle
cask dash
cask boxcryptor
cask quicklook-json
cask 1password
cask qlstephen
cask tripmode
cask onyx
cask qlcolorcode
cask vmware-fusion
cask qlimagesize
cask google-chrome
cask xquartz
cask quicklook-csv
cask zotero
cask alfred
cask skitch

tap caskroom/versions
cask java8

tap argon/mas

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty

# App Store applications
appstore 451732904 App Language Chooser (1.0)
appstore 961632517 Be Focused Pro (1.6.2)
appstore 417375580 BetterSnapTool (1.8)
appstore 409222199 Cyberduck (6.3.3)
appstore 408981434 iMovie (10.1.8)
appstore 409183694 Keynote (7.3.1)
appstore 539883307 LINE (5.5.1)
appstore 408519351 SeaSky Video Converter (1.8.5)
appstore 1278508951 Trello (2.10.0)
appstore 409789998 Twitter (4.3.2)
appstore 415166115 Typist (2.4.0)
appstore 497799835 Xcode (9.2)
