
# tap repositories and their packages

tap caskroom/cask

# Other Homebrew packages
brew jpeg
brew libde265
brew libheif
brew libpng
brew x265

# Other Cask applications
cask boxcryptor
cask google-photos-backup-and-sync
cask grammarly
