[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_post_source = '''
let ignore_globs = ['**/node_modules/**', '**/vendor/bundle/**', '**/bower_components/**', '**/tmp/cache/**']
call unite#custom#source('file_rec,file_rec/async', 'ignore_globs', ignore_globs)"
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['eruby', 'html']
hook_add = '''
let g:user_emmet_settings = {
  \   'indentation': '  '
  \ }
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']
on_map = ['<Plug>(EasyAlign)']
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
nmap <Leader>a <Plug>(EasyAlign)
'''
