#!/bin/bash
run_brew() {
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if has "brew"; then
    echo "Updating Homebrew..."
    brew update && brew upgrade
    [[ $? ]] && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    # preinstall taps
    brew tap 'caskroom/cask'
    brew tap 'argon/mas'
    brew tap 'homebrew/core'
    brew tap 'homebrew/bundle'
    brew tap 'sanemat/font'
    brew tap 'caskroom/fonts'
    brew tap 'caskroom/versions'
    brew tap 'beeftornado/rmtree'
    
    if  [ ! -f ${HOME}/.Brewfile ]; then
      ln -snfv ${DOT_DIRECTORY}/.Brewfile ${HOME}/.Brewfile
    fi

    brew bundle install --global
    [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
  fi
}
