memodir = "/Users/ytamai/Dropbox/.memo/"
editor = "code"
column = 20
selectcmd = "peco"
grepcmd = "/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg -n --no-heading -S ${PATTERN} ${FILES}"
assetsdir = ""
pluginsdir = "/Users/ytamai/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""